[package]
name = "willow"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.5.2"
serde = "1.0.136"
serde_derive = "1.0.136"
notify = { version = "8.1.0", features = ["serde"] }
clap = { version = "4.5.45", features = ["derive"] }