watchers:
  - path: "/Users/username/Downloads"
    recursive: true
    rules:
      - event: "created"
        conditions:
          - type: "extension"
            value: "jpg"
        actions:
          - type: "move"
            destination: "/Users/username/Pictures/"
      - event: "modified"
        conditions:
          - type: "extension"
            value: "pdf"
        actions:
          - type: "move"
            destination: "/Users/username/Documents/PDFs/"
